Birthday/Birthday/urls.py
from django.contrib import admin
from django.urls import path
from Birthday_app import views
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^Birthday_app/', include('Birthday_app.urls'))

]

Birthday/Birthday_app/urls.py
from django.conf.urls import url
from Birthday_app import views

app_name = 'Birthday_app'

urlpatterns=[
    url(r'^relative/$', views.relative, name="relative"),
    url(r'^other/$', views.other, name="other"),
    url(r'^base/$', views.base, name="base"),
]

Birthday/Birthday_app/models.py
from django.db import models

# Create your models here.

Birthday/Birthday_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'Birthday_app/index.html')

def other(request):
    return render(request, 'Birthday_app/other.html')

def base(request):
    return render(request, 'Birthday_app/base.html')

def relative(request):
    return render(request, 'Birthday_app/relative_url_templates.html')

Birthday/templates/Birthday_app/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Heena Malik</title>
  <link rel="stylesheet" href="./style.css">
  <style>
  /************************/
#nav{
  border:none;

}
.navbar{
padding:5px;
}
#hov a{
  margin-top:-10px;
  padding: 0px 10px;
  font-family:'Dancing Script' , 'Helvetica', sans-serif;
  font-weight:700;
  color:gold;
}
#listed{
  font-family:'Indie Flower','Arial',sans-serif;
  list-style: none;
  padding: 0px;
}
#listed a{
  padding: 20px 20px;
  margin: auto;
  font-size: 15px;
  font-weight:800;
  text-decoration: none;
  color: #ECF0F1;
  }
#listed li a:hover{
    color: gold;
    font-weight:300;
    background: rgba(255, 255, 255, 0.1);
    background-repeat: repeat;
    height: 100%;
    width: auto;
  }
/**********************/
#main-pic{
  margin-top:70px;
}
#main-pic .container{
  color:#fff;
  font-size:30px;
  position:relative;
  width:50%;
  left:20%;
}
#main-pic h1{
  font-family:'Permanent Marker','Arial',sans-serif;
  //border:1px solid black;
   font-size:50px;
}
#main-pic h3{
   font-family:'Indie Flower','Arial',sans-serif;
   font-size:30px;
  font-weight:800;
}
.jumbotron{
  display: flex;
  justify-content:center;
  align-items: center;
  text-align:center;
  background-image: url('https://www.vets4pets.com/siteassets/species/dog/puppy/husky-puppy-on-dog-walk.jpg?w=585&scale=down');
 //object-fit: contain;
   background-position:center center;
  background-repeat:no-repeat;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
   height: 75vh;
    width: 100%;
    overflow: hidden;
 // height:360px;
  //border:1px solid black;
}
#main-pic button[type="button"]{
  font-family:'Permanent Marker','Arial',sans-serif;
  text-transform:uppercase;
  color:#05A8AA;
  background:#fff;
  font-size:15px;
  font-weight:500;
  padding:10px 10px;
  margin:auto;
  margin-top:10px;
  border-radius:5px;
  border:1px solid #fff;
}
#main-pic button[type="button"]:hover{
  color:#fff;
  background:#05A8AA;
  border:1px solid #05A8AA;
}
/**********************/
#main{
  padding-bottom:20px;
}
#gallery{
    padding: 0px 50px;
    max-width: 1200px;
    text-align: center;
    margin: auto;
		margin-top: 40px;
    margin-bottom:20px;
}
.card {
  background-color: dodgerblue;
  color: white;
  text-align:center;
  // padding: 1rem;
  padding: 10rem 2rem;
  height: 5rem;
}
.cards {
  max-width: 1200px;
  margin: 0 auto;
  display: grid;
  grid-gap: 1rem;
}
.parent{
    //width: 45%;
      margin: 5px;
   // height: 300px;
    border: 1px solid none;
    overflow: hidden;
    position: relative;
    display: inline-block;
	  cursor: pointer;
}
.child{
    height: 100%;
    width: 100%;
    background-size: cover;
    background-repeat: no-repeat;
    -webkit-transition: all .5s;
    -moz-transition: all .5s;
    -o-transition: all .5s;
    transition: all .5s;
}
/*****************************/
.card1 {
  background-image: url(https://library.bc.edu/theme/img/news/2017-05/dog_jackson.png);
}
.card2{
  background-image: url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-cat-wearing-sunglasses-while-sitting-royalty-free-image-1571755145.jpg);
}
.card3{
  background-image: url(https://media.vivagoal.com/2022/02/Ronaldo-Diminta-Kreatif-Jangan-Selebrasi-Siuuu-Melulu.jpg);
  background-position:center center;
}
.card4{
  background-image: url(https://static2.tripoto.com/media/filter/tst/img/745287/SpotDocument/1573009576_1573009463689.jpg);
  background-position:center center;
}
.card5{
   background-image: url(https://i.pinimg.com/originals/43/c5/b7/43c5b7fb2d7517d00f587ed1626cdf99.jpg);

}
.card6{
   background-image: url(https://www.awesomecuisine.com/wp-content/uploads/2007/11/Pani-Puri.jpg);

}
.card7{
    background-image: url(https://liveferal.com/wp-content/uploads/2017/08/20170801-BLewis-Dear-Trail-Curmudgeon-1-1080x675.jpg);
  background-position:center center;
}
.card8{
   background-image: url(https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pink-select-2021?wid=940&hei=1112&fmt=png-alpha&.v=1645572315935);
  background-position:center center;
}
.card9{
   background-image: url(https://cdn.isha.ws/public/wallpapers/wallpaper/Shiva-Wallpaper-blue-purple-sky.jpg);
  background-position:left top;
}
.card10{
  background-image: url( https://upload.wikimedia.org/wikipedia/commons/6/63/Golden_Temple_nighttime.jpg);
  background-position:center center;
}
.card11{
  background-image: url( https://admin.itsnicethat.com/images/92qePGux-EkXt5xV3Fmixw3pGrM=/165245/format-webp%7Cwidth-1440/5d3978c37fa44cbd220015b1.jpg);
  background-position:center center;
}
.card12{
  background-image: url(https://images.moneycontrol.com/static-mcnews/2018/07/Starbucks-final.png?impolicy=website&width=770&height=431);
  background-position:center center;

}


/*****************************/
.parent:hover .child, .parent:focus .child {
    -ms-transform: scale(1.2);
    -moz-transform: scale(1.2);
    -webkit-transform: scale(1.2);
    -o-transform: scale(1.2);
    transform: scale(1.2);
}

.parent:hover .child:before, .parent:focus .child:before {
    display: block;
}

.parent:hover span, .parent:focus span {
  display:table-cell;
   // display: block;
}
span {
 display:none;
 margin: 0;
  position: absolute;
  top: 50%;
  left:32%;
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}
input[type="button"]{
  width:120px;
 height:40px;
 background-color:#05A8AA;
 border-radius:10px;
 border:none;
 color:white;
 font-weight:bold;
 font-family:'Permanent Marker','Arial',sans-serif;
  text-transform:uppercase;
 font-size:17px;
}

.child:before {
    content: "";
    display: none;
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    background-color: rgba(42, 46, 48,0.7);
}
/***************************************/
#see-more{
  text-align:center;
  display:block;
  //border:1px solid black;
   margin-bottom:20px;
  width:20%;
  margin:auto;
}
#see-more button[type="button"]{
  font-family:'Permanent Marker','Arial',sans-serif;
  text-transform:uppercase;
  color:#fff;
  background:#05A8AA;
  font-size:15px;
  font-weight:500;
  padding:10px 10px;
  margin:auto;
  margin-top:0px;
  border-radius:5px;
  border:1px solid #fff;
}
#see-more button[type="button"]:hover{
  color:#fff;
  background:rgba(5,168,170,0.5);
  border:1px solid #05A8AA;
}
/*****************************/
#foot{
  background:rgb(42, 46, 48);
  margin:0px;
  padding:10px 0px;
  height:auto;
}
#foot p{
  padding-top:5px;
  font-size:15px;
  color:gold;
}
/***************************************/
@media (min-width: 600px) {
  .cards { grid-template-columns: repeat(2, 1fr); }

}
@media (max-width:767px)  {
  /*make logo and in the middle*/
.navbar-brand{
  width:98%;
  max-width: 100%;
  display: block;
  height:auto;
  margin:auto;
  margin-bottom:0px;
  //border:1px solid yellow;
 // background:white;
}
#hov a h1{
    display:inline-block;
    margin:auto;
    text-align:center;
     margin-top:7px;
    // border:1px solid black;
  }
  #main-pic{
    margin-top:140px;
  }

  /*******************/
  .navbar-nav{
    text-align:center;
  }
  #listed a{
   // border:1px solid white;
    padding:5px 0px;
    font-size:15px;
  }
  #listed{
   // border:2px solid red;
    margin-top:0px;
    margin-bottom:0px;
  }
  }
@media (max-width:700px){
  span{
    left:29%;
  }
}
@media (max-width:650px){
  span{
    left:25%;
  }
}
@media (max-width:595px){
    span{
    left:34%;
  }
}
@media (max-width:400px){
  #main-pic h1{
    font-size:35px;
  }
  #main-pic h3{
      font-size:25px;
  }
    span{
     left:25%;
  }
}
@media (min-width: 1000px) {
  .cards { grid-template-columns: repeat(3, 1fr); }
}

  </style>
</head>
<body>
<!-- partial:index.partial.html -->
<!--https://css-tricks.com/zooming-background-images/-->

<html>
 <head>
    <title>Happy Birthday Heena Malik</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
   <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Permanent+Marker&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
   <header id="header">
      <nav class="navbar navbar-inverse navbar-fixed-top .navbar-right" id="nav">
        <div class="container-fluid">
          <div class="navbar-header" id="hov">
             <a class="navbar-brand text-center" href="#"><h1>Heena Malik</h1></a>
          </div>
          <ul class="nav navbar-nav navbar-right" id="listed">
             <li><a href="{% url 'Birthday_app:other' %}"><i class="fas fa-paw"></i> FireWorks <i class="fas fa-paw"></i></a></li>
             <li><a href="#"><i class="fas fa-paw"></i> Mohankumar <i class="fas fa-paw"></i></a></li>
             <li><a href="#"><i class="fas fa-paw"></i> Shweta&nbsp;Malik <i class="fas fa-paw"></i></a></li>
          </ul>
        </div>
      </nav>
      </header>
    <section class="jumbotron page-holder bg-cover " id="main-pic">
      <div class="container">
          <h1>Hi HeenaMalik</h1>
          <h3>Lot of Dogs need your attention</h3>
          <a href="{% url 'Birthday_app:base' %}"class="btn btn-primary btn-lg animated flip">QUEEN</a>
      </div>
      </section>
    <section id="main">
     <!-- <section id="gallery">
        <div class="cards" >
             <div class="card">ONE</div>
             <div class="card">TWO</div>
             <div class="card">THREE</div>
             <div class="card">FOUR</div>
             <div class="card">FIVE</div>
             <div class="card">SIX</div>
             <div class="card">SEVEN</div>
             <div class="card">EIGHT</div>
             <div class="card">NINE</div>
             <div class="card">TEN</div>
             <div class="card">ELEVEN</div>
             <div class="card">TWELVE</div>
          </div>
        </section>-->
       <section id="gallery">
        <div class="cards" >
          <div class="parent" onclick="">
             <div class="card child card1">
              <!-- <a href="#" class="button">buttt</a>-->
               <span><input type="button" value="Bow Bow"></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card2">
               <span><input type="button" value="Meow.."></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card3">
                <span><input type="button" value="Siuuu.."></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card4">
               <span><input type="button" value="Visit me"></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card5">
                <span><input type="button" value="Fav View"></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card6">
               <span><input type="button" value="Yummy"></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card7">
                <span><input type="button" value="Let's Go"></span>
            </div>
          </div>
          <div class="parent" onclick="">
             <div class="card child card8">
                <span><input type="button" value="Buy me"></span>
            </div>
          </div>
           <div class="parent" onclick="">
             <div class="card child card9">
               <span><input type="button" value="Fav God"></span>
             </div>
          </div>
           <div class="parent" onclick="">
             <div class="card child card10">
                <span><input type="button" value="Temple"></span>
             </div>
          </div>
           <div class="parent" onclick="">
             <div class="card child card11">
                <span><input type="button" value="Burger"></span>
             </div>
          </div>
           <div class="parent" onclick="">
             <div class="card child card12">
                <span><input type="button" value="Coffee"></span>
             </div>
          </div>
       </div>
        </section>
    </section>

  </body>

  </html>
<!-- partial -->

</body>
</html>